# Copyright 2020, 2025, Oracle Corporation and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence CE GitHub Actions Examples - Build.
# ---------------------------------------------------------------------------

name: Examples Build

on:
  workflow_dispatch:
    inputs:
      runner:
        default: ubuntu-latest
        required: true
        type: string
  workflow_call:
    inputs:
      runner:
        default: ubuntu-latest
        required: true
        type: string

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Print Maven & Java version
      run: mvn -version

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

      # Build and Test examples
    - name: build-test-examples
      timeout-minutes: 180
      shell: bash
      env:
        MAVEN_USER: ${{ secrets.MavenUser }}
        MAVEN_PASSWORD: ${{ secrets.MavenPassword }}
      run: |
        echo "Building and Running - Examples"
        export DEV_ROOT=$(pwd)
        mvn --file prj/pom.xml --batch-mode -U -e -s .github/maven/settings.xml -P-modules -DskipTests clean install
        mvn --file prj/pom.xml --batch-mode -e -s .github/maven/settings.xml -Pmodules,-coherence -nsu -DskipTests clean install
        mvn --file prj/pom.xml --batch-mode -U -e -s .github/maven/settings.xml -Pexamples -nsu clean install

    # Upload build artifacts for diagnosing failures
    - name: Build Artifacts test logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output
        path: prj/examples/**/target/test-output/**/*
        if-no-files-found: ignore

    - name: Build Artifacts test reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: failsafe-surefire-test-reports
        path: prj/examples/**/target/*-reports/**/*
        if-no-files-found: ignore

    - name: Build Artifacts core dumps
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: core-dumps
        path: prj/examples/**/core.*
        if-no-files-found: ignore

    - name: Build Artifacts compiler replays
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: compiler-replay-logs
        path: prj/examples/**/replay_pid*.log
        if-no-files-found: ignore
